### ISSUE TITLE
NRE on Android when a new activity is opened

### ISSUE THREAD

**Issue by pravincar** [dansiegel/Prism.Plugin.Popups#166] opened 2020-09-24 09:35 UTC
This issue has been observed on Android 9 and 10
The problem exists on the current master branch as well as v7.2.1046 

The issue is reproducible in the sample app that is part of this project too. I have attached a video showing steps to reproduce the issue along with the code I modified to log the exception.

Essentially Android creates a new activity which I expect should return the app to the initial page.
I have also tried creating this scenario with Xamarin Forms and Rg.Plugins.Popup (without Prism). In this case, the navigation seems to work fine.

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Prism.Common.PageUtilities.GetCurrentPage (Xamarin.Forms.Page mainPage) [0x00002] in /_/src/Forms/Prism.Forms/Common/PageUtilities.cs:255 
  at Prism.Plugin.Popups.PopupPageNavigationService.DoPush (Xamarin.Forms.Page currentPage, Xamarin.Forms.Page page, System.Nullable`1[T] useModalNavigation, System.Boolean animated, System.Boolean insertBeforeLast, System.Int32 navigationOffset) [0x00218] in 
```

[Screen Recording 2020-09-24 at 2.51.09 PM.mov.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/5274893/Screen.Recording.2020-09-24.at.2.51.09.PM.mov.zip)

[samples.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/5274897/samples.zip)

**Comment by dansiegel** [comment] 2020-09-24 14:44
So to confirm your steps are:

- Navigate to `NavigationPage/SomePage`
- Navigate to a PopupPage
- Hit the hardware back on the Android device

To be honest I'm not sure that this is going to be fixable since PrismApplication is listening for an event that I cannot exactly make it stop listening to, so the error is actually coming from inside Prism because as far as Prism.Forms understands you only have a NavigationPage with a single child which cannot be navigated back from..

**Comment by pravincar** [comment] 2020-09-25 10:47
Thanks for the quick response. The steps you have listed are correct. We have also observed this behaviour on clicking a notification to get back into the app on Android.
https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/activity-lifecycle/#back-vs-home

I did some further investigation today and I agree that it may not be fixable in this codebase. Essentially, Android creates a new activity which fires OnCreate and OnInitialized (in PrismApplication). 

At this stage it seems like Prism is still holding onto some previous state. Prism believes that the current page is a popup page whereas MainPage is null.
I'm not aware of the architecture of Prism but it seems like Prism should clear all cached state in this situation and start fresh. 

I believe this will affect a lot of apps that use this framework since this is a common use case. What do you suggest as the next steps?

**Comment by jbachelor** [comment] 2020-09-25 16:04
Thanks for those details, @pravincar. I have been wrestling with a seemingly different issue, but based on what you're saying I believe it may be the same root cause. In my case, however, the issue occurs for both Android and iOS, and appears to be the result of displaying a popup, and then immediately navigating following the popup's dismissal:
1. Show popup.
2. When popup is dismissed, the handler is called in the original ViewModel.
3. The popup response handler makes a navigation call to a new ContentPage, but prepends "../" in order to remove the page from the navigation stack ([details on this technique here](https://brianlagunas.com/whats-new-in-prism-for-xamarin-forms-7-0/)). Without adding the "../", the navigation works without issue.

I've found that if I add a `Task.Delay` of about 500ms or more, the issue will not occur. Without a pause to allow the popup to clear out completely prior to making a navigation call, things seem to get confused, resulting in a NullReferenceException.

The null ref error I hit is in the `RemovePagesFromNavigationPage` method in [Prism's PageNavigationService](https://github.com/PrismLibrary/Prism/blob/261790736d7f73491d6baffcd35de6afee27f97b/src/Forms/Prism.Forms/Navigation/PageNavigationService.cs#L489) . Specifically it is the line, `var navigationPage = (NavigationPage)currentPage.Parent;`. When things get confused between the popup still closing and the navigation to a new ContentPage, it winds up in this method where the currentPage has a null Parent. Then it tries to call into the navigation stack of that null Parent.

The exception I get is:
```
######## MyNavService.RemovePagesFromNavigationPage
EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
  at MyCoolApp.Services.PrismNavOverride.MyNavService.RemovePagesFromNavigationPage (Xamarin.Forms.Page currentPage, System.Collections.Generic.List`1[T] pagesToRemove) [0x0002b] in /Users/Shared/src/AppsAndSuch/MyCoolApp1/MyCoolApp/Services/PrismNavOverride/MyNavService.cs:471 
  at MyCoolApp.Services.PrismNavOverride.MyNavService.RemoveAndPush (Xamarin.Forms.Page currentPage, System.String nextSegment, System.Collections.Generic.Queue`1[T] segments, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x00187] in /Users/Shared/src/AppsAndSuch/MyCoolApp1/MyCoolApp/Services/PrismNavOverride/MyNavService.cs:462 
  at MyCoolApp.Services.PrismNavOverride.MyNavService.ProcessNavigation (Xamarin.Forms.Page currentPage, System.Collections.Generic.Queue`1[T] segments, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x0012a] in /Users/Shared/src/AppsAndSuch/MyCoolApp1/MyCoolApp/Services/PrismNavOverride/MyNavService.cs:367 
  at MyCoolApp.Services.PrismNavOverride.MyNavService.NavigateInternal (System.Uri uri, Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x0014f] in /Users/Shared/src/AppsAndSuch/MyCoolApp1/MyCoolApp/Services/PrismNavOverride/MyNavService.cs:335 . Priority: High. Timestamp:2020-09-24 11:22:30Z.
```

I am working on a small sample app to reproduce the issue, and will report back here when I have it.

@dansiegel - Thanks so much for all of your help in troubleshooting this issue!

**Comment by jbachelor** [comment] 2020-09-29 02:51
I have a [small sample app](https://github.com/jbachelor/XFPrismSample/tree/localNavSvc) that I believe reproduces the problem. Make sure you are looking at the "localNavSvc" branch.

**Comment by pravincar** [comment] 2020-09-29 06:43
@jbachelor I've seen the problem that you have described in some scenarios too. However, it is different from the issue I have reported here.
I have implemented a workaround in my app to get rid of the Task.Delay. 

Create a popup pop observable which subscribes to the PopupNavigation instance in Rg.Plugins.Popup
```
public IObservable<System.Reactive.EventPattern<PopupNavigationEventArgs>> PopupPopObservable
            = Observable.FromEventPattern<PopupNavigationEventArgs>(
                (h) => PopupNavigation.Instance.Popped += h, (h) => PopupNavigation.Instance.Popped -= h);
```

Wait for the popup to get cleared before any further navigation

```
await PopupPopObservable.Take(1);
```
This may work for you too.

**Comment by jbachelor** [comment] 2020-10-05 16:02
Thanks so much for this, @pravincar! I'll have to look into that idea... Need to read up a bit on Rx first.  :) 

@dansiegel - Should I open up a separate issue for what I've experienced?

**Comment by jdarmody** [comment] 2021-02-28 11:56
@dansiegel - Seems like the NRE isn't happening anymore in the latest copy of master?

Also the handling of the Android hardware back button in the sample app can be done by overriding the OnBackPressed in the MainActivity (see https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started#android-back-button). But I think maybe we need a Prism.Plugin.Popups version of Rg.Plugins.Popup.SendBackPressed()? 

A Prism.Plugin.Popups.SendBackPressed() could do an "isPreventClose" check (see https://github.com/rotorgames/Rg.Plugins.Popup/blob/d14e753a349cdf52e2ae2d33e91c66de0582fe63/Rg.Plugins.Popup/Platforms/Android/Popup.cs) and then if the top popup can be closed, the PopupPageNavigationService can execute it's GoBackInternal with all the required PageUtilities methods called (e.g. OnNavigatedFrom, OnNavigatedTo).

**Comment by dansiegel** [comment] 2021-02-28 15:15
@pravincar as this has been reported by both @jbachelor and @jdarmody as not happening anymore I'm going to close the issue. If it continues to please let me know and we'll reopen the issue.

**Closed by dansiegel** 2021-02-28 15:15 UTC
Labels: bug, to verify
