### ISSUE TITLE
Open PopupPage from action sheet

### ISSUE THREAD

**Issue by beylkhanovdamir** [dansiegel/Prism.Plugin.Popups#42] opened 2017-04-27 09:14 UTC
@dansiegel 

After update on the latest XF release 2.3.4 I noticed that when I try open my popup page by clicking on the button from action sheet , my app is crashes. 
In output log I see the next info:

> Error: An error occurred while executing MTouch. Please check the logs for more details.
The app has been terminated.

This is how I'm adding my action sheet button (I'm using a Prism PageDialogService):

`var updateLocationAction = ActionSheetButton.CreateButton("Change Store", UpdateLocation);`
`actions.Add(updateLocationAction);`

And this is how I'm calling popup page:

`private async void UpdateLocation()
		{ 
await _navigationService.PushPopupPageAsync("UpdateLocationPopupView");}`

**Comment by beylkhanovdamir** [comment] 2017-04-27 20:52
@dansiegel any ideas?

**Comment by dansiegel** [comment] 2017-04-27 20:54
I won't have time to look into this until at least tomorrow. In the mean time I would delete your obj and bin folders. You may also try deleting your packages folder and doing a full restore and with a fresh build. I've noticed sometimes after updating Xamarin things get messed up and it requires obliterating all of the build artifacts.

**Comment by beylkhanovdamir** [comment] 2017-04-27 21:23
@dansiegel but it's not working on device too

**Comment by dansiegel** [comment] 2017-04-28 05:03
@beylkhanovdamir I'm unable to reproduce your issue. I'm running one of my apps with Xamarin Forms 2.3.4.231 and Prism.Plugin.Popups without an issue.

**Comment by beylkhanovdamir** [comment] 2017-05-01 01:06
@dansiegel 
probably the main reason is that you are using PCL with Profile78 project type vs .netstandard 1.3 from my side

**Comment by beylkhanovdamir** [comment] 2017-05-01 01:08
do you plan how resolve these project differences?

**Comment by dansiegel** [comment] 2017-05-01 06:04
@beylkhanovdamir not sure I follow you. The plugin uses Profile259, the same as Prism. I won't be updating this library to NetStandard until Prism has made the switch.

**Comment by beylkhanovdamir** [comment] 2017-05-01 15:05
@dansiegel 
I've another question. If I opened my popup, then when I close it, I need call Gobackasync in navigationservice, which calling init of my previous view, but I didn't need reinit data for previous view. How I can fix it?

**Comment by beylkhanovdamir** [comment] 2017-05-01 16:41
>@beylkhanovdamir I'm unable to reproduce your issue. I'm running one of my apps with Xamarin Forms 2.3.4.231 and Prism.Plugin.Popups without an issue.

do you test in android emulator? or ios simulator?
I noticed that crash is reproducing only in ios simulator. i.e. on android everything is fine

**Comment by dansiegel** [comment] 2017-05-01 16:42
I always suggest testing on a real device. I usually deploy to my Android and iOS devices for local testing

**Comment by beylkhanovdamir** [comment] 2017-05-01 16:46
@dansiegel 

ok. will test on device, thx

please get answer on question about working with popup in 2.x version

**Comment by beylkhanovdamir** [comment] 2017-05-01 16:54
> I always suggest testing on a real device. I usually deploy to my Android and iOS devices for local testing

just tested on my iphone, popup is not appearing

**Comment by beylkhanovdamir** [comment] 2017-05-01 19:49
I don't know why, but it's now working only if popup calling from action sheet and on ios

**Comment by dansiegel** [comment] 2017-05-01 20:25
@beylkhanovdamir if you have a demo project that can replicate your issue it would be a lot easier for me to try to help you.

**Comment by beylkhanovdamir** [comment] 2017-05-01 21:34
@dansiegel 
no problems.  I've taken a fork from your master branch and added some changes to reproduce my issue on ios with calling popup from action sheet. BTW, I've updated XF to latest version and added your plugin as nuget package to project

You can download [this sample from here](https://www.dropbox.com/s/omk4vhtwemtcih5/Prism.Plugin.Popups-Popup_Issue.zip?dl=0)

Also I recorded a short screencast with 2 issues. One of this these with my problem, and which one with your button for popup launching
Check pls - https://www.screencast.com/t/GC1FoGTu

P.S. if you are reproduce this issue then too, please notify me about that

**Comment by dansiegel** [comment] 2017-05-01 21:59
@beylkhanovdamir the issue of the buttons not working, seems to be some weird bug with the Commands not firing. I still need to look into this more. I'm going to be busy working on some Prism updates for the next week but then hopefully I can focus some attention to this after that. If you have a fork and would like to look into the issue yourself, I'm always happy to accept PR's.

**Comment by Mutasem1980** [comment] 2017-06-12 13:55
**Workaround**

task.delay(1)
_navigationservice.PushPopupPageAsync(..

**Comment by dansiegel** [comment] 2017-08-30 00:27
This issue should have been fixed in 2.0.0-pre2... please let me know if that is not the case and we can reopen this.

**Closed by dansiegel** 2017-08-30 00:27 UTC
