### ISSUE TITLE
Popup within Popup

### ISSUE THREAD

**Issue by mr5z** [dansiegel/Prism.Plugin.Popups#82] opened 2018-12-19 09:18 UTC
Hi,

I am trying to navigate from a PopupPage to another PopupPage. Navigating back to the previous page using `NavigationService.GoBackAsync()`, it returns back an Exception although the popup page was visually dismissed.

Exception message:

> at Prism.Plugin.Popups.PopupPageNavigationService+<InvokeOnNavigatedToAsync>d__8.MoveNext () [0x0012a] in D:\\a\\1\\s\\src\\Prism.Plugin.Popups\\PopupPageNavigationService.cs:135 \n--- End of stack trace from previous location where exception was thrown ---\n  at Prism.Plugin.Popups.PopupPageNavigationService+<GoBackInternal>d__4.MoveNext () [0x00194] in D:\\a\\1\\s\\src\\Prism.Plugin.Popups\\PopupPageNavigationService.cs:57 "

**Edit**: Using `NavigationService.ClearPopupStackAsync()` yields the same result. This is happening both in iOS and Android.

**Comment by danilkurkin1** [comment] 2019-02-20 08:42
Happening to me too. Plugin is working but Application output shows that there was an System.NullReferenceException: Object reference not set to an instance of an object at PopupPageNavigationService.cs:135

**Comment by canmrt** [comment] 2019-05-07 16:18
I also have the same exception captured via prism ILoggerFacade.

> 
"System.NullReferenceException: Object reference not set to an instance of an object\n  at Prism.Plugin.Popups.PopupPageNavigationService.InvokeOnNavigatedToAsync (System.Object view, Prism.Navigation.INavigationParameters parameters) [0x0012a] in D:\\a\\1\\s\\src\\Prism.Plugin.Popups\\PopupPageNavigationService.cs:135 \n  at Prism.Plugin.Popups.PopupPageNavigationService.GoBackInternal (Prism.Navigation.INavigationParameters parameters, System.Nullable`1[T] useModalNavigation, System.Boolean animated) [0x00194] in D:\\a\\1\\s\\src\\Prism.Plugin.Popups\\PopupPageNavigationService.cs:57 "

**Comment by dansiegel** [comment] 2019-05-08 03:55
closing for no reproduction.

**Closed by dansiegel** 2019-05-08 03:55 UTC

**Comment by arbesoft** [comment] 2019-07-03 11:46
Hi,
here is an example how to reproduce the exception. After ClearPopupStackAsync the INavigationResult is Success False. 
Steps:
1. Clone Repo: https://github.com/arbesoft/popupsample
2. Add Breakpoint at PopUpViewModel Line 30
3. Start Debugging --> Go To MasterDetailPage --> Then click openpopup --> then Click Back Button.

Result: You will get a NavigationResult with Success == False and Exception.

Regards

Osman

**Comment by thisisthekap** [comment] 2019-07-04 08:58
Also experiencing this issue. @dansiegel Would vote for reopening this issue.

**Comment by HelenMamalaki** [comment] 2019-07-24 14:06
I am also getting the same problem when navigating back from a Rg.Plugins.Popup.Page back to a TabbedPage. I get the same NullRefrenceException as @canmrt but on iOS only. On Android it works as expected. It looks like @abesoft has reproduced the issue. @dansiegel can this be opened please?

**Comment by akamud** [comment] 2019-08-23 17:00
Same problem here.
