### ISSUE TITLE
VTable setup of type Prism.Plugin.Popups.PopupPageNavigationService failed on iOS

### ISSUE THREAD

**Issue by mfranc28** [dansiegel/Prism.Plugin.Popups#126] opened 2019-12-16 14:55 UTC
Having this error on iOS, Android version is ok

**Comment by dansiegel** [comment] 2019-12-16 15:40
closing as this is not an actionable issue. There are no details or reproduction.

the error VTable setup typically occurs with linker issues and when you have binary incompatibilities. Since you've provided no details it's impossible for me to provide more insight into this.

**Closed by dansiegel** 2019-12-16 15:40 UTC
