### ISSUE TITLE
Prism.Plugin.Popups 7.2.0.573 strange behavior with navigation from Popup

### ISSUE THREAD

**Issue by KSemenenko** [dansiegel/Prism.Plugin.Popups#106] opened 2019-08-23 07:45 UTC
Hi, I have discovered strange behavior compared to the previous version.
My flow:
1. NavigateTo ContentPage
2. From ContentPage NavigateTo PopUpPage
3. From PopUpPage NavigateTo ContentPage

In in the previous version, when I called NavigateTo with the PopUp page, it turned out that I switched to another page and the popup closed.

Now the popup is closing, but navigation does not happen.

**Comment by JohnTraDolta** [comment] 2019-08-26 09:14
i am able to reproduce this

**Comment by JohnTraDolta** [comment] 2019-08-26 10:59
as a workaround til they fix it you can do this 

var currentNavigationProxy = PrismApplicationBase.Current.NavigationProxy;
var NavigationParameters = new NavigationPage(new PageToNavigateTo());
await currentNavigationProxy.PushModalAsync(NavigationParameters);


this worked for me

**Comment by dansiegel** [comment] 2019-08-29 05:22
please provide a sample that reproduces the issue

**Comment by ksevery** [comment] 2019-09-05 10:18
@dansiegel Here is a sample that reproduces the issue.

[PrismPopupsNavigationIssue.zip](https://github.com/dansiegel/Prism.Plugin.Popups/files/3578728/PrismPopupsNavigationIssue.zip)

**Comment by lypefm** [comment] 2019-09-27 16:57
I have the same problem ... I try to navigate from a popup to a page and it just doesn't open.

**Comment by andreybel** [comment] 2019-10-02 18:58
I have same problem
@ksevery when I'm trying to use this syntax:
 await NavigationService.NavigateAsync("myapp:///OtherPage")
all next opened pages are not ContentPage.
They are opening as PopupPage (whitout title and tabbar in my case)

**Comment by ksevery** [comment] 2019-10-02 19:28
@andreybel Keep in mind - the "myapp:///" part of that navigation clears out your whole Navigation Stack and starts over from scratch. If you want to open a page within a NavigationPage, you need to specify that. Same if you're trying to open a page that should be able to navigate back to another page, e.g. if you want to navigate to Page 2, but that page should be able to do back navigation to Page 1, your navigation path will look like this: "myapp:///NavigationPage/Page1/Page2".

**Comment by andreybel** [comment] 2019-10-02 19:43
I found my mistake
@ksevery  Thank you so much!

**Comment by jitendrajadav** [comment] 2019-10-12 12:12
I have a same problem

**Comment by TKNos** [comment] 2019-10-21 06:01
I can confirm this behaviour after updating to **7.2.0.573**.

**Comment by JohnTraDolta** [comment] 2019-10-21 11:30
Is it possible to make a pull request, my work is blocked by this.

Thanks in advance

**Comment by TKNos** [comment] 2019-10-21 12:02
> Is it possible to make a pull request, my work is blocked by this.

I could not find a proper solution while I investigated the issue. Reverting the commit mentioned above would re-open issue #81 which it should fix. Just wanted to support @dansiegel with my findings: maybe it helps him find a solution for this issue.

**Comment by JohnTraDolta** [comment] 2019-10-21 12:07
Okay :) 
i guess i could do that...
Thanks :)

**Comment by dansiegel** [comment] 2019-10-21 12:14
@JohnTraDolta yes it is very much possible to submit a PR... the CI is setup as well so that as soon as any PR is merged you'll be able to pull it from the dev feed

**Comment by JohnTraDolta** [comment] 2019-10-21 12:18
Okay i will look into it when i am off from work today

**Comment by MerlinSOI** [comment] 2019-10-30 13:10
I also noticed that. Even if the popup navigation stack is empty (e.g. I call GoBackAsync previously), I still face the same issue - navigation to the content page is not working...

**Comment by TKNos** [comment] 2019-11-22 05:23
@JohnTraDolta Any insights on this issue?

**Comment by jitendrajadav** [comment] 2019-11-22 07:01
I got updated one version "**7.2.0.759**" but still it won't solved this problem

**Comment by nrooban** [comment] 2019-12-03 03:24
I believe, Rg.Plugins.Popup had compatibility issues with iOS 13 and they fixed it. 
Since Prism.Plugin.Popups depends on Rg.Plugins.Popup. They also updated with the version 7.2+. 
But unfortunately, they have not fixed in version 2.2.0.293.

Since Prism.Plugin.Popups fixed in 7.2+ and also its depends on Prism Library version 7.2 project must be updated with Xamarin 4+. 

Since Prism V7+  wont fire OnNavigatingTo the as per there release note
[https://github.com/PrismLibrary/Prism/releases/tag/v7.2.0.1367] 
This all issue occured. 

If Prism.Plugin.Popups can give an update to version 2.2.0.293 with Rg.Plugins.Popup bug fix of iOS 13. we can use the same old Xamarin (V3) and Prism versions 7.1 avoid the major change in the project.

====================================
In nutshell We need an update from Prism.Plugin.Popups in the version 2.2.0.293 with Rg.Plugins.Popup bug fix of iOS 13

**Comment by dansiegel** [comment] 2019-12-03 04:29
@nrooban 

- Prism 7.2 does not target Xamarin.Forms 4+. It targets 3.6 and is tested with everything between 3.6 and the 4.4 preview
- If there is an issue with Rg.Plugins.Popup, as long as there isn't a breaking change there you should be able to update the reference
- I don't do service releases for previous versions unless I'm paid for it. It's extra work for which I have no personal interest otherwise.

**Comment by nrooban** [comment] 2019-12-03 06:53
@dansiegel Thank you for the update. I truly understand that we are using prism for free and we cant expect more service for free. 

Just to be cleared. Please let me know that, in order to work prism.plugin.popups perfect in iOS 13 we must use version 7.2 along with Prism 7.2. If yes, We should do other break updates from prism 7.1 to 7.2 if we encountered any issues in our apps. 

Am I correct to say that? Please clarify. Thank you

**Comment by jitendrajadav** [comment] 2020-01-02 06:08
Any update on this issue?

**Comment by dansiegel** [comment] 2020-01-04 01:54
@JohnTraDolta was this something you were still working on?

**Comment by jitendrajadav** [comment] 2020-01-06 09:51
Yes I have problem with my existing application earlier it was working fine but once I have updated it won't work form pop up to navigation please fixe this

**Comment by JohnTraDolta** [comment] 2020-01-06 10:11
Yes i'm sorry but i havn't found the time for fix this

**Comment by kerbooo** [comment] 2020-01-23 08:21
Same problem is here :(

**Comment by jitendrajadav** [comment] 2020-02-06 09:32
Any updated on this issue I am not sure when this issue is going to updated my entire work is blocked due to this problem almost 5 month

**Comment by dansiegel** [comment] 2020-02-06 15:09
@jitendrajadav a few things here... 

- This is an open source library not a paid product. I work on this is my spare time. 
- Priorities go to issues that affect me, and issues that are affecting my [GitHub Sponsors](https://github.com/sponsors/dansiegel) which sadly nobody on this thread is. 
- I do take PRs

**Comment by kerbooo** [comment] 2020-02-06 15:59
@dansiegel yes your are mostly right and thank you for your good works. But I think you are a not a kind person and selfish man. My suggestion for you please get out from Open Source world. Because you are not working without a coin as I understood.

**Comment by ksevery** [comment] 2020-02-06 16:04
@kerbooo This is a comment that is not in any way useful to the discussion here. Open Source does not mean the library needs to be fixed by the creator whenever there is an issue. It means other people can contribute to make it better and you don't have to pay to use it, but it comes with the risk of it either being dropped for support or your issue not getting fixed if no one gets around to fixing the specific issue. If you need this to be fixed - grab the library's code, fix the issue and submit a PR. As noted by @dansiegel this library is something he works on in his spare time - he is in no way obliged to work on an issue with it if he has other things he wants to do during said time. 
Once again, if you want this issue fixed so badly it's impacting your work - you're free to fix the issue yourself. Or toss a coin to @dansiegel so he fixes it :)

**Comment by kerbooo** [comment] 2020-02-06 16:20
@ksevery thank you for your explain. There are so many people in the world. Every person is different. @dansiegel is important person because of his works. But he should claim his valuable works. I am learning good things from his works but I am not good developer as @dansiegel to solve this issue. I think there are so many people. I have read so many comment as he wrote as above. If you are good as @dansiegel please fix that. We will be glad you too.

**Comment by aritchie** [comment] 2020-02-06 16:26
@dansiegel gives a TON to the community - many times more than he takes.  He's a fantastic guy all round.  To call him selfish and not kind @kerbooo is extremely rude, unnecessary, and hypocritical on your part.  You don't know him personally.  You have zero repos and zero contributions on github.  It is you who should leave OSS.

@jitendrajadav you keep complaining you are blocked and asking for updates.  Fix it yourself.  If you don't know how, why are you using the library in the first place?  You can pay Dan to fix it.  Honestly, asking for continual updates though, is also extremely rude.

**Comment by kerbooo** [comment] 2020-02-06 16:53
@aritchie you can say everthing but you can not say hypocritical to me. Because I have wrote as How I felt. Yes I do not have any repo because I am a newbie. @dansiegel is master. I think you too. But masters should be helpfull and stronger.

**Comment by dansiegel** [comment] 2020-02-06 17:05
@kerbooo your comments are incredibly rude and not at all helpful either to the issue at hand or to your goal of putting me in a mood where I want to spend my free time fixing this issue. I could charge for this if I wanted but I choose to make it freely available to help people. If you find my work so helpful then I would suggest you show your gratitude with a monthly contribution as a Sponsor. If you find you need support some my higher sponsorship levels do come with limited support. Do not confuse any of this with me owing anybody anything, because I don't owe you anything for the thousands of hours I've invested in giving back to the Xamarin Community at my personal expense.

Lastly let me just say that if you continue these unhelpful and toxic comments you will find yourself to be the first and only person banned from my repos.

**Comment by andreybel** [comment] 2020-02-06 18:11
Hi all!
Maybe it will be useful to someone:
I am using MessagingCenter () to navigate from a pop-up page to another page. This is not perfect, but it works for me)

**Comment by kerbooo** [comment] 2020-02-06 20:16
@dansiegel OK. How would you like to do you can. You can block me. I did not write wrong things. Anyway thank you for your good works. I have just shared my opinions. I think so many people feel like me. I am not a boss just a employee but If you need I can share my money with you. Good work.

**Comment by kerbooo** [comment] 2020-02-07 04:54
Hi all. That is last comment for me. Bug and new feature request are different things. If the code has bug that means it can not be useable. Yes all of us use open source things and we should help. Inform about bug to owner is a kind of help too. But firstly the owner of the code claim her or him works on the bug status. Because owner knows codes logic better than anyone. If the bug does not fix nobody use the code. Please understand me clear.

**Comment by nrooban** [comment] 2020-02-07 06:51
@kerbooo, I my self decided to discontinue to use Prism even Xamarin and moved to flutter. Do not limit your self as you have the answer from the creator of this plugin. So this plugin was useful, but not anymore, may be in future. Thank you @dansiegel for the support and understanding.

**Comment by ksevery** [comment] 2020-03-05 09:21
Hey everyone, I've submitted a PR that fixes the issue, at least in my very conservative testing. If anyone would like to, you can take the branch and test in your own cases so we can find any issues that may come up as a result of the fix. The PR is #136

**Closed** 2020-03-31 13:55 UTC
Labels: bug

**Comment by JohamVan** [comment] 2020-04-02 00:03
@dansiegel How long should it take for the Nuget package to have these changes? 
Thanks advance

**Comment by dansiegel** [comment] 2020-04-06 14:11
@JohamVan builds are always available via the CI feed within a few minutes of a PR being merged. That said I'll be releasing this on NuGet this morning.

**Comment by JohamVan** [comment] 2020-04-06 18:24
@dansiegel thank you very much.
